organization: sd
component: cams
lead_email: vp@foobar.com
team_email: team@foobar.com
users: &users
  name1:
  name2:
subcomponents:
  - name: foobar
    type: tomcat
    users:
      <<: *users
      name3:
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      loadbalancer_port: 8082
      service_port: 8080
    telemetry:
      health_url: /
      notification_email: foo@bar.com
    domain_names:
      - domain_name: foobar.com
        environment: prd
      - domain_name: foobar2.com
        environment: prd
    default_servers:
      - host: 0.0.0.0
        port: 8080
        environment: stg
      - host: 0.0.0.0
        port: 8080
        environment: prd
    dependencies:
      - component: cams
        subcomponent: cat
        latency: foo
        identifier: barbaz
        read_only: true
      - component: cams
        subcomponent: foobar
        latency: foo
        identifier: barbas3
    metadata:
      foo: bar
      sticky_session: sessionkey
  - name: cat
    type: mysql
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    default_servers:
      - host: 0.0.0.0
        port: 8080
        environment: prd
    ports:
      loadbalancer_port: 8081
      service_port: 8080
    dependencies:
      - component: cams
        subcomponent: cat
        latency: 10
    metadata:
      read_only: true
  - name: baz
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      loadbalancer_port: 8083
      service_port: 8080
    dependencies: []
