dendrite_version: 1
organization: sd
namespace: cams
lead_email: vp@foobar.com
team_email: team@foobar.com
services:
  - name: foobar
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      advertised_port: 8081
      listening_port: 8080
    dependancies:
      - namespace: cams
        name: cat
        latency: foo
  - name: cat
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      advertised_port: 8081
      listening_port: 8080
    dependancies:
      - namespace: cams
        name: foobar
        latency: foo
  - name: baz
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      advertised_port: 8081
      listening_port: 8080
    dependancies: []
