organization: sd
component: cams
lead_email: vp@foobar.com
team_email: team@foobar.com
subcomponents:
  - name: foobar
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      loadbalancer_port: 8082
      service_port: 8080
    telemetry:
      health_url: /
      notification_email: foo@bar.com
    default_servers:
      - host: 192.168.1.1
        port: 8080
        environment: stg
      - host: 50.312.312.312
        port: 8080
        environment: prd
    dependencies:
      - component: cams
        subcomponent: cat
        latency: foo
      - component: cams
        subcomponent: foobar
        latency: foo
  - name: cat
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      loadbalancer_port: 8081
      service_port: 8080
    dependencies:
      - component: cams
        subcomponent: foobar
        latency: foo
  - name: baz
    type: tomcat
    deploy:
      repository: git@github.com:yagnik/dendrite
      package: dendrite
    scale:
      min_instance_count: 1
      max_instance_count: 5
    ports:
      loadbalancer_port: 8083
      service_port: 8080
    dependencies: []
