dendrite:
  organization: sd
  dc: ggn1
  env: dev
  zk_hosts:
    - localhost:2181
  nerve_config_path: /opt/smartstack/conf/nerve.yml
  synapse_config_path: /opt/smartstack/conf/synapse.yml
  services_source: /vagrant/services/services/ 

synapse:
  haproxy:
    reload_command: sudo service haproxy reload
    config_file_path: /etc/haproxy/haproxy.cfg
    socket_file_path: /var/haproxy/stats.sock
    do_writes: true
    do_reloads: true
    do_socket: false
    global:
    - daemon
    - user haproxy
    - group haproxy
    - maxconn 4096
    - log     127.0.0.1 local0
    - log     127.0.0.1 local1 notice
    - stats   socket /var/haproxy/stats.sock mode 666 level admin
    defaults:
    - log      global
    - option   dontlognull
    - maxconn  2000
    - retries  3
    - timeout  connect 5s
    - timeout  client  1m
    - timeout  server  1m
    - option   redispatch
    - balance  roundrobin
    extra_sections:
      listen stats :9999:
      - mode http
      - stats enable
      - stats uri /
      - stats refresh 5s
