dendrite:
  organization: sd
  dc: ggn1
  env: dev
  zk_hosts:
    - localhost:2181
  bind_to_all: true
  sticky: true
  nerve_config_path: /opt/smartstack/conf/nerve.yml
  synapse_config_path: /opt/smartstack/conf/synapse.yml
  services_source: conf/services
  valid_app_types:
    - tomcat
    - mysql
    - mongodb
    - aerospike
    - cassandra
    - jar
  http_app_types:
    - tomcat

synapse:
  server_options: check inter 2s rise 3 fall 2
  haproxy:
    reload_command: sudo service haproxy reload
    config_file_path: /etc/haproxy/haproxy.cfg
    socket_file_path: /var/haproxy/stats.sock
    do_writes: true
    do_reloads: true
    do_socket: false
    shared_frontend:
    - "bind 127.0.0.1:8082"
    - "bind 127.0.0.1:8089"
    global:
    - daemon
    - user haproxy
    - group haproxy
    - maxconn 4096
    - log     127.0.0.1 local0
    - log     127.0.0.1 local1 notice
    - stats   socket /var/haproxy/stats.sock mode 666 level admin
    defaults:
    - log      global
    - option   dontlognull
    - maxconn  2000
    - retries  3
    - timeout  connect 5s
    - timeout  client  1m
    - timeout  server  1m
    - option   redispatch
    - balance  roundrobin
    extra_sections:
      peers syncinghaproxy:
      - peer foobar 0.0.0.0:1024
      listen stats :9999:
      - mode http
      - stats enable
      - stats uri /
      - stats refresh 5s
