namespace: cams
lead_email: vp@foobar.com
team_email: team@foobar.com
services:
  - name: foobar
    type: tomcat
    repo: git@github.com:yagnik/dendrite/services/pom.xml
    package_name: dendrite
    ports:
      advertised_port: 8081
      running_port: 8080
    dependancies:
      - name: cat
        latency: foo
  - name: cat
    type: tomcat
    repo: git@github.com:yagnik/dendrite
    package_name: dendrite
    error_budget: None
    ports:
      advertised_port: 8081
      lb_port: 8080
    dependancies:
      - name: foobar
        latency: foo
  - name: baz
    type: tomcat
    repo: git@github.com:yagnik/dendrite
    package_name: dendrite
    error_budget: None
    ports:
      advertised_port: 8081
      running_port: 8080
    dependancies: []
